index:
    path: /
    controller: App\Controller\HomeController::index

getTeams:
  path: /teams
  controller: App\Controller\TeamController::getTeams

addTeams:
  path: /teams/add
  controller : App\Controller\TeamController::addTeams

getPlayers :
  path: /players
  controller : App\Controller\PlayerController::getPlayers

addPlayers :
  path: /players/add
  controller : App\Controller\PlayerController::addPlayers

TeamProfile :
  path: /teams/{id}
  controller : App\Controller\TeamController::getOneTeam
