<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWoK3O16\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWoK3O16/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWoK3O16.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWoK3O16\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWoK3O16\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'WoK3O16',
    'container.build_id' => '33422518',
    'container.build_time' => 1551257995,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerWoK3O16');
